# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get -y install docker
    docker run --rm -v $(pwd):/workdir earlephilhower/gcc-cross bash /workdir/buildall.sh 4.8
  displayName: 'Build'
